Fix #51 : Modified Login Page Responsive
CSwala/cswala.github.io pull request #53
Opened 2021-06-22 14:23 UTC by Vasanth1009

## Explanation
Fixes #51: Modified the login page and footer responsively

## Type of Change:
- Code
- User Interface

## Checklist
- [x] The PR title starts with "Fix #bugnum: "followed by a short, clear summary of the changes. ( If this PR fixes part of an issue, prefix the title with "Fix part of #bugnum: ...")
- [x] The PR explanation includes the words "Fixes #bugnum: ..." ( or "Fixes part of #bugnum" if the PR only partially fixes an issue ).
- [x] The PR does not contain any unnecessary auto-generated code from Android Studio.
- [x] The PR does not break any part of the existing code.
- [x] The PR creator have carefully read & adhere to the contributing guidelines of the project.
- [x] The PR is raised for an issue that has been assigned to you.
- [x] The PR is made to the branch that's **called** "develop".
- [x] The PR is raised from a branch that is up-to-date with "develop".

![unknown](https://user-images.githubusercontent.com/55186278/122941806-5a165b80-d393-11eb-8e29-63a6e45f811f.png)

2021-06-25 15:00 UTC, 5tupidbrain approved these changes

2021-06-25 15:09 UTC, 5tupidbrain requested changes
# Fix

![image](https://user-images.githubusercontent.com/37737242/123445051-25094380-d5f5-11eb-974e-ced8851c4853.png)

```
- Make it better for Desktop.! (Less Height and add columns)
```

2021-06-28 07:32 UTC, Vasanth1009 commented
Please Review my code updated footer responsively for mobile and desktop as well

2021-06-28 07:50 UTC, riturajjain2000 approved these changes

2021-06-28 08:08 UTC, 5tupidbrain approved these changes

2021-06-28 08:08 UTC, merged